refactor: start page (#1134)
This refactors the start page but also introduce some changes to its UI. Once there's a new design for the page, the only review needed from UI/UX is if it doesn't violate much of the user experience before the new page comes. Main UX breaking change was the removal of the editable text from the chart name, leaving this to be performed when the chart is opened instead of directly on the main page.

Many UI/UX changes were already validated with @Sebastianskar1, @magdalenarut678 and @ericsteinbeldring. But it's always good to get a ✅ again.

## Visible UI/UX changes

- The error toast will not appear stacked anymore. Instead, an error message will come as an Infobox statically at the top of the page.
- List view is now based on the cogs table component
- Date/Time is formatted using the cogs helper for date + tooltips to show full date/time
- After #1136 gets merged, the formatter will respect the language defined by the user
- Loading states were introduced. The transition to the actual state is still not perfect, but I would prefer doing this in the new start page
- Table is now responsive
- Grid view is responsive. The number of items per row depends on the screen size
- Grid Item width/height is not based on percentage anymore. It's fixed in pixels. This helps in responsiveness and avoid redraw on the plotly previews which can be costly for the browser in long lists.
- Grid Item now has an elevation defined by cogs as a card (z-4)
- Grid Items with too long titles get overflowed with ellipsis (...). Titles have a tooltip to show the entire title. Can be improved later detecting if the text is overflowing but it's technically tricky (Cogs does not forward the ref of the element so we can measure it)

## Main code refactorings to be discussed (No final decision. Everything in the technical side is open to change and discussion)

- No loading of operations in the page opening. This avoids the stacking of error messages and consequently removes calculations from chart previews
- Added models for myCharts and publicCharts that brings only the data needed by the components. Nothing else. The models don't use recoil because they are not reused anywhere. But it could be implemented.
- Added helper in `models/plotlyChart` to fetch the timeseries and give the plotly props in order to display the previews. Not sure if it's the best place. Let's discuss.
- Added hook for creating a new chart. Not sure about what's the best place for it but separated it in the `firebase/currentChart` model folder once it represents the C in CRUD of the current chart.
- Total separation between UI and Data Models. The UI components must not be aware about how the data was generated or how the data should be processed. All necessary actions are exposed as event handlers (`onClick`, `onChartDuplicate`, etc) so the actions actually happen outside of the UI level. Also, the properties of the components shouldn't match the shape of the data in the source database (f.ex. `ChartListTable` component should not be aware of the Firebase data model `Chart`). This ensures only the data needed for displaying the UI is described in the component props, making it simpler for the developer to understand what he/she is working on during the UI phase. Passing an exact copy of the database model to the component generates encapsulation, makes the developer lose context and easily get lost once a field name in database can represent other things that the UI should not be aware (Ex: `workflowCollection` in Firebase vs `calculationList` in the Frontend)
- Data Model organization - In this specific case, there are not so many data sources, so everything was kept in the page component. In other cases, like the chart view page, the data models can be separated in container components under the page component. How to decide? Whatever makes sense in terms of organization. Only rule applied is "Leave the data model out of the UI components"
- Data Model Implementation - The data models needed for the page were implemented as hooks representing the state and its actions. How the developer will organize and expose the functions it's up to the developer. F.Ex.:

```
{
  list: myChartList.orderedList,
  sortList,
  filterList,
  deleteChart,
  duplicateChart,
  duplicatePublicChart,
  loading: myChartList.loading,
  error: myChartList.error,
};
```

- Storybooks created for all UI components exploring the maximum of the code coverage possible. Storybook is improving and soon we will start creating coverage reports for interaction testing. I requested the Jest coverage flag in https://github.com/storybookjs/test-runner/issues/116. Hope it comes soon.
- Added an extra translation function `getTranslationsFromComponent` to simplify the work with translations. The function allows you to fetch a subset of the translations in the main component. Using this, the main component will have all translation keys from all components flattened. Inspired in how Material UI did for the data grid component. This is not a breaking change so it can be introduced to other components as we get going.